name: flutter_lyra
description: This package allows you to use the methods from the lyra android and ios native sdks in Flutter
version: 0.4.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_lyra_android
      ios:
        default_package: flutter_lyra_ios

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_lyra_android: 
    path: ../flutter_lyra_android
  flutter_lyra_ios: 
    path: ../flutter_lyra_ios
  flutter_lyra_platform_interface: 
    path: ../flutter_lyra_platform_interface
dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  plugin_platform_interface: ^2.0.0
