name: flutter_lyra_android
description: Android implementation of the flutter_lyra plugin
version: 0.4.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: flutter_lyra
    platforms:
      android:
        package: tech.bam.flutter_lyra.android
        pluginClass: FlutterLyraPlugin
        dartPluginClass: FlutterLyraAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_lyra_platform_interface: 
    path: ../flutter_lyra_platform_interface
dev_dependencies:
  analyzer: ^5.13.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
